### ISSUE TITLE
Repository set up? 

### ISSUE THREAD

**Issue by kclarke3** [kclarke3/Katies_Stats_Project#1]
@AaronGullickson Hi Aaron, I believe I set up the repository. Thanks! (edited @ 6:07 pm)

I was unable to render my qmd file and not sure what the error code means

ompilation failed- error
LaTeX Error: Environment CSLReferences undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.260 \renewenvironment{CSLReferences}
                                      [2] % #1 hanging-ident, #2 entry spacing 

see /Users/katieclarke/Desktop/soc 512/Katies_Stats_Project/paper/main_manuscript.log for more information.

**Comment by AaronGullickson** [comment]
That is the error with my template, that we talked about in class.  If you click the terminal tab in the lower left of RStudio, you can then enter:

```
quarto update extensions AaronGullickson/aog-article-quarto
```

That will update to the latest version which should work. Alternatively, you can go into `paper/main_manuscript.qmd` and change the line in the YAML header that says `aog-article-pdf` to just `pdf`. It won't look as nice, but it will work.
