### ISSUE TITLE
Get Data; Prepare Analytical Datasheet

### ISSUE THREAD

**Issue by kclarke3** [kclarke3/Katies_Stats_Project#2]
Hi @AaronGullickson, this is me sending a notification that the Data has been obtained and cleaned! Thank you so so much for using class time to help me get on track, I really appreciate it. I believe the datasheet assignment is complete but wanted to confirm.

**Comment by AaronGullickson** [comment]
Thats great. Did you get the corrected 2017 data? If so, remember to add it to to the `bind_rows` command to get the 2017 data added to the full data.
